export type CityEntry = {
  name: string;
  lat: string;
  lng: string;
  timezone: string;
};

// Coordinates sourced from mapsofindia.com/lat_long/tamilnadu/ and latlong.net
export const TN_CITIES: CityEntry[] = [
  { name: "Chennai, Tamil Nadu, India",              lat: "13.0667",  lng: "80.2833",  timezone: "Asia/Kolkata" },
  { name: "Coimbatore, Tamil Nadu, India",           lat: "11.0000",  lng: "77.0000",  timezone: "Asia/Kolkata" },
  { name: "Madurai, Tamil Nadu, India",              lat: "9.9667",   lng: "78.1667",  timezone: "Asia/Kolkata" },
  { name: "Tiruchirappalli, Tamil Nadu, India",      lat: "10.8333",  lng: "78.7667",  timezone: "Asia/Kolkata" },
  { name: "Salem, Tamil Nadu, India",                lat: "11.6500",  lng: "78.2000",  timezone: "Asia/Kolkata" },
  { name: "Tirunelveli, Tamil Nadu, India",          lat: "8.7333",   lng: "77.7333",  timezone: "Asia/Kolkata" },
  { name: "Tiruppur, Tamil Nadu, India",             lat: "11.1085",  lng: "77.3411",  timezone: "Asia/Kolkata" },
  { name: "Erode, Tamil Nadu, India",                lat: "11.3333",  lng: "77.7667",  timezone: "Asia/Kolkata" },
  { name: "Vellore, Tamil Nadu, India",              lat: "12.9167",  lng: "79.1833",  timezone: "Asia/Kolkata" },
  { name: "Thoothukudi, Tamil Nadu, India",          lat: "8.8000",   lng: "78.1833",  timezone: "Asia/Kolkata" },
  { name: "Thanjavur, Tamil Nadu, India",            lat: "10.7833",  lng: "79.1667",  timezone: "Asia/Kolkata" },
  { name: "Dindigul, Tamil Nadu, India",             lat: "10.3667",  lng: "78.0000",  timezone: "Asia/Kolkata" },
  { name: "Cuddalore, Tamil Nadu, India",            lat: "11.7167",  lng: "79.8167",  timezone: "Asia/Kolkata" },
  { name: "Kancheepuram, Tamil Nadu, India",         lat: "12.8333",  lng: "79.7500",  timezone: "Asia/Kolkata" },
  { name: "Kumbakonam, Tamil Nadu, India",           lat: "10.9667",  lng: "79.4167",  timezone: "Asia/Kolkata" },
  { name: "Nagercoil, Tamil Nadu, India",            lat: "8.1833",   lng: "77.4833",  timezone: "Asia/Kolkata" },
  { name: "Karur, Tamil Nadu, India",                lat: "10.9667",  lng: "78.1167",  timezone: "Asia/Kolkata" },
  { name: "Namakkal, Tamil Nadu, India",             lat: "11.2167",  lng: "78.2167",  timezone: "Asia/Kolkata" },
  { name: "Pudukkottai, Tamil Nadu, India",          lat: "10.3833",  lng: "78.8667",  timezone: "Asia/Kolkata" },
  { name: "Ramanathapuram, Tamil Nadu, India",       lat: "9.3667",   lng: "78.8667",  timezone: "Asia/Kolkata" },
  { name: "Virudhunagar, Tamil Nadu, India",         lat: "9.5833",   lng: "77.9500",  timezone: "Asia/Kolkata" },
  { name: "Krishnagiri, Tamil Nadu, India",          lat: "12.5333",  lng: "78.2667",  timezone: "Asia/Kolkata" },
  { name: "Dharmapuri, Tamil Nadu, India",           lat: "12.1333",  lng: "78.2167",  timezone: "Asia/Kolkata" },
  { name: "Villupuram, Tamil Nadu, India",           lat: "11.9500",  lng: "79.5333",  timezone: "Asia/Kolkata" },
  { name: "Nagapattinam, Tamil Nadu, India",         lat: "10.7667",  lng: "79.8333",  timezone: "Asia/Kolkata" },
  { name: "Perambalur, Tamil Nadu, India",           lat: "11.2333",  lng: "78.9333",  timezone: "Asia/Kolkata" },
  { name: "Tenkasi, Tamil Nadu, India",              lat: "8.9667",   lng: "77.3167",  timezone: "Asia/Kolkata" },
  { name: "Tiruvannamalai, Tamil Nadu, India",       lat: "12.2500",  lng: "79.1167",  timezone: "Asia/Kolkata" },
  { name: "Sivakasi, Tamil Nadu, India",             lat: "9.4500",   lng: "77.8000",  timezone: "Asia/Kolkata" },
  { name: "Pollachi, Tamil Nadu, India",             lat: "10.6500",  lng: "77.0500",  timezone: "Asia/Kolkata" },
  { name: "Mettupalayam, Tamil Nadu, India",         lat: "11.3000",  lng: "76.9833",  timezone: "Asia/Kolkata" },
  { name: "Hosur, Tamil Nadu, India",                lat: "12.7333",  lng: "77.8667",  timezone: "Asia/Kolkata" },
  { name: "Ambur, Tamil Nadu, India",                lat: "12.7833",  lng: "78.7167",  timezone: "Asia/Kolkata" },
  { name: "Vaniyambadi, Tamil Nadu, India",          lat: "12.6833",  lng: "78.6500",  timezone: "Asia/Kolkata" },
  { name: "Arakkonam, Tamil Nadu, India",            lat: "13.0833",  lng: "79.7167",  timezone: "Asia/Kolkata" },
  { name: "Tindivanam, Tamil Nadu, India",           lat: "12.2333",  lng: "79.7000",  timezone: "Asia/Kolkata" },
  { name: "Vriddhachalam, Tamil Nadu, India",        lat: "11.5333",  lng: "79.4000",  timezone: "Asia/Kolkata" },
  { name: "Mannargudi, Tamil Nadu, India",           lat: "10.6667",  lng: "79.4833",  timezone: "Asia/Kolkata" },
  { name: "Chidambaram, Tamil Nadu, India",          lat: "11.4000",  lng: "79.7333",  timezone: "Asia/Kolkata" },
  { name: "Paramakudi, Tamil Nadu, India",           lat: "9.5167",   lng: "78.6500",  timezone: "Asia/Kolkata" },
  { name: "Palani, Tamil Nadu, India",               lat: "10.4500",  lng: "77.5167",  timezone: "Asia/Kolkata" },
  { name: "Sankarankovil, Tamil Nadu, India",        lat: "9.0167",   lng: "77.5833",  timezone: "Asia/Kolkata" },
  { name: "Sattur, Tamil Nadu, India",               lat: "9.3500",   lng: "77.9667",  timezone: "Asia/Kolkata" },
  { name: "Rajapalayam, Tamil Nadu, India",          lat: "9.4500",   lng: "77.6000",  timezone: "Asia/Kolkata" },
  { name: "Aruppukkottai, Tamil Nadu, India",        lat: "9.5167",   lng: "78.1333",  timezone: "Asia/Kolkata" },
  { name: "Sivaganga, Tamil Nadu, India",            lat: "9.8500",   lng: "78.4833",  timezone: "Asia/Kolkata" },
  { name: "Mayiladuthurai, Tamil Nadu, India",       lat: "11.1000",  lng: "79.7000",  timezone: "Asia/Kolkata" },
  { name: "Chengalpattu, Tamil Nadu, India",         lat: "12.7000",  lng: "80.0167",  timezone: "Asia/Kolkata" },
  { name: "Ooty (Udagamandalam), Tamil Nadu, India", lat: "11.4000",  lng: "76.7333",  timezone: "Asia/Kolkata" },
  { name: "Coonoor, Tamil Nadu, India",              lat: "11.3500",  lng: "76.7833",  timezone: "Asia/Kolkata" },
  { name: "Yercaud, Tamil Nadu, India",              lat: "11.8000",  lng: "78.2167",  timezone: "Asia/Kolkata" },
  { name: "Kodaikanal, Tamil Nadu, India",           lat: "10.2167",  lng: "77.5333",  timezone: "Asia/Kolkata" },
  { name: "Rameswaram, Tamil Nadu, India",           lat: "9.2833",   lng: "79.3667",  timezone: "Asia/Kolkata" },
  { name: "Bodinayakkanur, Tamil Nadu, India",       lat: "10.0167",  lng: "77.4000",  timezone: "Asia/Kolkata" },
  { name: "Periyakulam, Tamil Nadu, India",          lat: "10.1167",  lng: "77.5833",  timezone: "Asia/Kolkata" },
  { name: "Udumalaipettai, Tamil Nadu, India",       lat: "10.6000",  lng: "77.2833",  timezone: "Asia/Kolkata" },
  { name: "Gobichettipalayam, Tamil Nadu, India",    lat: "11.4500",  lng: "77.4333",  timezone: "Asia/Kolkata" },
  { name: "Bhavani, Tamil Nadu, India",              lat: "11.4500",  lng: "77.6833",  timezone: "Asia/Kolkata" },
  { name: "Attur, Tamil Nadu, India",                lat: "11.6000",  lng: "78.6500",  timezone: "Asia/Kolkata" },
  { name: "Rasipuram, Tamil Nadu, India",            lat: "11.4667",  lng: "78.1667",  timezone: "Asia/Kolkata" },
  { name: "Dharapuram, Tamil Nadu, India",           lat: "10.7500",  lng: "77.5667",  timezone: "Asia/Kolkata" },
  { name: "Pallipalayam, Tamil Nadu, India",         lat: "11.3833",  lng: "77.7167",  timezone: "Asia/Kolkata" },
  { name: "Tiruchengode, Tamil Nadu, India",         lat: "11.3833",  lng: "77.9333",  timezone: "Asia/Kolkata" },
  { name: "Gudiyatham, Tamil Nadu, India",           lat: "12.9500",  lng: "78.9167",  timezone: "Asia/Kolkata" },
  { name: "Vandalur, Tamil Nadu, India",             lat: "12.8833",  lng: "80.0833",  timezone: "Asia/Kolkata" },
  { name: "Mahabalipuram, Tamil Nadu, India",        lat: "12.6167",  lng: "80.2333",  timezone: "Asia/Kolkata" },
  { name: "Tiruvallur, Tamil Nadu, India",           lat: "13.1500",  lng: "79.9500",  timezone: "Asia/Kolkata" },
  { name: "Pondicherry, Tamil Nadu, India",          lat: "11.9333",  lng: "79.8333",  timezone: "Asia/Kolkata" },
  { name: "Srirangam, Tamil Nadu, India",            lat: "10.8667",  lng: "78.6833",  timezone: "Asia/Kolkata" },
  { name: "Papanasam, Tamil Nadu, India",            lat: "10.9333",  lng: "79.2833",  timezone: "Asia/Kolkata" },
  { name: "Ponneri, Tamil Nadu, India",              lat: "13.0333",  lng: "80.2500",  timezone: "Asia/Kolkata" },
  { name: "Panruti, Tamil Nadu, India",              lat: "11.7833",  lng: "79.5833",  timezone: "Asia/Kolkata" },
  { name: "Pattukkottai, Tamil Nadu, India",         lat: "10.4333",  lng: "79.3667",  timezone: "Asia/Kolkata" },
  { name: "Vedaranyam, Tamil Nadu, India",           lat: "10.3833",  lng: "79.8500",  timezone: "Asia/Kolkata" },
  { name: "Lalgudi, Tamil Nadu, India",              lat: "10.8667",  lng: "78.8167",  timezone: "Asia/Kolkata" },
  { name: "Musiri, Tamil Nadu, India",               lat: "10.9500",  lng: "78.4500",  timezone: "Asia/Kolkata" },
  { name: "Valparai, Tamil Nadu, India",             lat: "10.3167",  lng: "76.9500",  timezone: "Asia/Kolkata" },
  { name: "Gudalur, Tamil Nadu, India",              lat: "11.5000",  lng: "76.4833",  timezone: "Asia/Kolkata" },
  { name: "Usilampatti, Tamil Nadu, India",          lat: "9.9667",   lng: "77.8000",  timezone: "Asia/Kolkata" },
  { name: "Srivilliputhur, Tamil Nadu, India",       lat: "9.5167",   lng: "77.6333",  timezone: "Asia/Kolkata" },
  { name: "Kovilpatti, Tamil Nadu, India",           lat: "9.1667",   lng: "77.8667",  timezone: "Asia/Kolkata" },
  { name: "Kadayanallur, Tamil Nadu, India",         lat: "9.0833",   lng: "77.3500",  timezone: "Asia/Kolkata" },
  { name: "Thirumangalam, Tamil Nadu, India",        lat: "9.8167",   lng: "77.9833",  timezone: "Asia/Kolkata" },
];
