packages:
  - "mobile"
  - "packages/*"
  - "web"
overrides:
  react-native-worklets: "0.8.3"
allowBuilds:
  '@firebase/util': true
  '@sentry/cli': true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
