"""Authoritative Tamil Muhurtham (wedding) naals, curated per published almanac.

Why this exists
---------------
Our panchangam engine's ``is_subha_muhurtham`` flag is intentionally broad —
it marks any day whose nakshatra/weekday/tithi are not disqualifying. A real
published Tamil almanac muhurtham list is far stricter (it also applies Tamil
month suitability, lagna windows, tithi+yoga+karana combinations, eclipse
avoidance, etc.), so the engine flags roughly 3x more days than the almanac.

For the *muhurtham-naal listing* we therefore treat a curated almanac list as
the source of truth, and use the engine only to (a) enrich each date with its
verified nakshatra / tithi / Tamil-month labels and (b) pick the best time
slot within the day. The enrichment below was generated by running the engine
over each curated date at the Chennai reference location and was cross-checked
against the same almanac's tithi/nakshatra event tables.

Source of dates + pirai: tamildailycalendar.com Tamil Muhurtham sheets.
2026: 55 dates; 25 Valarpirai / 30 Theipirai.
2027: 74 dates; 37 Valarpirai / 37 Theipirai.

Scope: only years with a sourced almanac sheet are listed. Callers must treat a
missing year as "not yet published" rather than falling back to calculation.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date


@dataclass(frozen=True, slots=True)
class MuhurthamNaal:
    """One curated muhurtham date, enriched with verified panchangam labels."""

    date: date
    weekday: str            # English weekday enum (e.g. "MONDAY")
    pirai: str              # "VALARPIRAI" (waxing) | "THEIPIRAI" (waning)
    tamil_month_index: int  # 0..11 (Chithirai=0 .. Panguni=11)
    tamil_day: int
    nakshatra_number: int   # 1..27 — the auspicious star driving the muhurtham
    nakshatra_name: str
    moon_rasi_number: int   # 1..12 — Moon's rasi (for Chandrashtama matching)
    moon_rasi_name: str
    tithi_number: int       # 1..30
    tithi_name: str
    paksha: str             # "SHUKLA" | "KRISHNA"


def _n(
    iso: str, weekday: str, pirai: str, tmi: int, td: int,
    nak_no: int, nak: str, rasi_no: int, rasi: str,
    tithi_no: int, tithi: str, paksha: str,
) -> MuhurthamNaal:
    return MuhurthamNaal(
        date=date.fromisoformat(iso),
        weekday=weekday,
        pirai=pirai,
        tamil_month_index=tmi,
        tamil_day=td,
        nakshatra_number=nak_no,
        nakshatra_name=nak,
        moon_rasi_number=rasi_no,
        moon_rasi_name=rasi,
        tithi_number=tithi_no,
        tithi_name=tithi,
        paksha=paksha,
    )


_MUHURTHAM_NAALS_2026: tuple[MuhurthamNaal, ...] = (
    _n("2026-01-28", "WEDNESDAY", "VALARPIRAI", 9, 14, 4, "ROHINI", 2, "Rishabam", 10, "DASAMI", "SHUKLA"),
    _n("2026-02-06", "FRIDAY", "THEIPIRAI", 9, 23, 13, "HASTHAM", 6, "Kanni", 20, "PANCHAMI", "KRISHNA"),
    _n("2026-02-08", "SUNDAY", "THEIPIRAI", 9, 25, 15, "SWATHI", 7, "Thulam", 22, "SAPTAMI", "KRISHNA"),
    _n("2026-02-13", "FRIDAY", "THEIPIRAI", 10, 1, 19, "MOOLAM", 9, "Dhanusu", 26, "EKADASI", "KRISHNA"),
    _n("2026-02-15", "SUNDAY", "THEIPIRAI", 10, 3, 21, "UTHIRADAM", 10, "Magaram", 28, "THRAYODASI", "KRISHNA"),
    _n("2026-02-16", "MONDAY", "THEIPIRAI", 10, 4, 22, "THIRUVONAM", 10, "Magaram", 29, "CHATHURDASI", "KRISHNA"),
    _n("2026-02-20", "FRIDAY", "VALARPIRAI", 10, 8, 26, "UTHIRATTATHI", 12, "Meenam", 3, "THRITHIYAI", "SHUKLA"),
    _n("2026-03-05", "THURSDAY", "THEIPIRAI", 10, 21, 12, "UTHIRAM", 6, "Kanni", 17, "DVITHIYAI", "KRISHNA"),
    _n("2026-03-06", "FRIDAY", "THEIPIRAI", 10, 22, 13, "HASTHAM", 6, "Kanni", 18, "THRITHIYAI", "KRISHNA"),
    _n("2026-03-08", "SUNDAY", "THEIPIRAI", 10, 24, 15, "SWATHI", 7, "Thulam", 20, "PANCHAMI", "KRISHNA"),
    _n("2026-03-15", "SUNDAY", "THEIPIRAI", 11, 1, 22, "THIRUVONAM", 10, "Magaram", 26, "EKADASI", "KRISHNA"),
    _n("2026-03-16", "MONDAY", "THEIPIRAI", 11, 2, 23, "AVITTAM", 10, "Magaram", 27, "DVADASI", "KRISHNA"),
    _n("2026-03-25", "WEDNESDAY", "VALARPIRAI", 11, 11, 5, "MIRUGASEERIDAM", 2, "Rishabam", 7, "SAPTAMI", "SHUKLA"),
    _n("2026-04-06", "MONDAY", "THEIPIRAI", 11, 23, 17, "ANUSHAM", 8, "Viruchigam", 19, "CHATHURTHI", "KRISHNA"),
    _n("2026-04-12", "SUNDAY", "THEIPIRAI", 11, 29, 22, "THIRUVONAM", 10, "Magaram", 25, "DASAMI", "KRISHNA"),
    _n("2026-04-13", "MONDAY", "THEIPIRAI", 11, 30, 23, "AVITTAM", 11, "Kumbam", 26, "EKADASI", "KRISHNA"),
    _n("2026-04-16", "THURSDAY", "THEIPIRAI", 0, 3, 26, "UTHIRATTATHI", 12, "Meenam", 29, "CHATHURDASI", "KRISHNA"),
    _n("2026-04-20", "MONDAY", "VALARPIRAI", 0, 7, 4, "ROHINI", 2, "Rishabam", 3, "THRITHIYAI", "SHUKLA"),
    _n("2026-04-23", "THURSDAY", "VALARPIRAI", 0, 10, 7, "PUNARPOOSAM", 3, "Mithunam", 7, "SAPTAMI", "SHUKLA"),
    _n("2026-04-30", "THURSDAY", "VALARPIRAI", 0, 17, 14, "CHITHIRAI", 6, "Kanni", 14, "CHATHURDASI", "SHUKLA"),
    _n("2026-05-08", "FRIDAY", "THEIPIRAI", 0, 25, 21, "UTHIRADAM", 10, "Magaram", 21, "SHASHTI", "KRISHNA"),
    _n("2026-05-13", "WEDNESDAY", "THEIPIRAI", 0, 30, 26, "UTHIRATTATHI", 12, "Meenam", 26, "EKADASI", "KRISHNA"),
    _n("2026-05-14", "THURSDAY", "THEIPIRAI", 0, 31, 27, "REVATHI", 12, "Meenam", 27, "DVADASI", "KRISHNA"),
    _n("2026-05-18", "MONDAY", "VALARPIRAI", 1, 4, 4, "ROHINI", 2, "Rishabam", 2, "DVITHIYAI", "SHUKLA"),
    _n("2026-05-28", "THURSDAY", "VALARPIRAI", 1, 14, 14, "CHITHIRAI", 7, "Thulam", 12, "DVADASI", "SHUKLA"),
    _n("2026-05-29", "FRIDAY", "VALARPIRAI", 1, 15, 15, "SWATHI", 7, "Thulam", 13, "THRAYODASI", "SHUKLA"),
    _n("2026-06-04", "THURSDAY", "THEIPIRAI", 1, 21, 21, "UTHIRADAM", 9, "Dhanusu", 19, "CHATHURTHI", "KRISHNA"),
    _n("2026-06-07", "SUNDAY", "THEIPIRAI", 1, 24, 23, "AVITTAM", 11, "Kumbam", 22, "SAPTAMI", "KRISHNA"),
    _n("2026-06-17", "WEDNESDAY", "VALARPIRAI", 2, 2, 7, "PUNARPOOSAM", 3, "Mithunam", 3, "THRITHIYAI", "SHUKLA"),
    _n("2026-06-18", "THURSDAY", "VALARPIRAI", 2, 3, 8, "POOSAM", 4, "Kadagam", 4, "CHATHURTHI", "SHUKLA"),
    _n("2026-06-24", "WEDNESDAY", "VALARPIRAI", 2, 9, 14, "CHITHIRAI", 7, "Thulam", 10, "DASAMI", "SHUKLA"),
    _n("2026-06-25", "THURSDAY", "VALARPIRAI", 2, 10, 15, "SWATHI", 7, "Thulam", 11, "EKADASI", "SHUKLA"),
    _n("2026-07-02", "THURSDAY", "THEIPIRAI", 2, 17, 21, "UTHIRADAM", 10, "Magaram", 17, "DVITHIYAI", "KRISHNA"),
    _n("2026-07-05", "SUNDAY", "THEIPIRAI", 2, 20, 24, "SADAYAM", 11, "Kumbam", 20, "PANCHAMI", "KRISHNA"),
    _n("2026-07-12", "SUNDAY", "THEIPIRAI", 2, 27, 4, "ROHINI", 2, "Rishabam", 28, "THRAYODASI", "KRISHNA"),
    _n("2026-08-23", "SUNDAY", "VALARPIRAI", 4, 7, 19, "MOOLAM", 9, "Dhanusu", 11, "EKADASI", "SHUKLA"),
    _n("2026-08-30", "SUNDAY", "THEIPIRAI", 4, 14, 26, "UTHIRATTATHI", 12, "Meenam", 17, "DVITHIYAI", "KRISHNA"),
    _n("2026-08-31", "MONDAY", "THEIPIRAI", 4, 15, 27, "REVATHI", 12, "Meenam", 18, "THRITHIYAI", "KRISHNA"),
    _n("2026-09-07", "MONDAY", "THEIPIRAI", 4, 22, 7, "PUNARPOOSAM", 3, "Mithunam", 26, "EKADASI", "KRISHNA"),
    _n("2026-09-13", "SUNDAY", "VALARPIRAI", 4, 28, 13, "HASTHAM", 6, "Kanni", 2, "DVITHIYAI", "SHUKLA"),
    _n("2026-09-17", "THURSDAY", "VALARPIRAI", 5, 1, 17, "ANUSHAM", 8, "Viruchigam", 6, "SHASHTI", "SHUKLA"),
    _n("2026-10-25", "SUNDAY", "VALARPIRAI", 6, 8, 27, "REVATHI", 12, "Meenam", 14, "CHATHURDASI", "SHUKLA"),
    _n("2026-10-30", "FRIDAY", "THEIPIRAI", 6, 13, 5, "MIRUGASEERIDAM", 3, "Mithunam", 20, "PANCHAMI", "KRISHNA"),
    _n("2026-11-01", "SUNDAY", "THEIPIRAI", 6, 15, 8, "POOSAM", 4, "Kadagam", 22, "SAPTAMI", "KRISHNA"),
    _n("2026-11-11", "WEDNESDAY", "VALARPIRAI", 6, 25, 17, "ANUSHAM", 8, "Viruchigam", 2, "DVITHIYAI", "SHUKLA"),
    _n("2026-11-13", "FRIDAY", "VALARPIRAI", 6, 27, 19, "MOOLAM", 9, "Dhanusu", 4, "CHATHURTHI", "SHUKLA"),
    _n("2026-11-15", "SUNDAY", "VALARPIRAI", 6, 29, 21, "UTHIRADAM", 10, "Magaram", 6, "SHASHTI", "SHUKLA"),
    _n("2026-11-16", "MONDAY", "VALARPIRAI", 6, 30, 22, "THIRUVONAM", 10, "Magaram", 7, "SAPTAMI", "SHUKLA"),
    _n("2026-11-20", "FRIDAY", "VALARPIRAI", 7, 4, 26, "UTHIRATTATHI", 12, "Meenam", 10, "DASAMI", "SHUKLA"),
    _n("2026-11-29", "SUNDAY", "THEIPIRAI", 7, 13, 8, "POOSAM", 4, "Kadagam", 21, "SHASHTI", "KRISHNA"),
    _n("2026-12-04", "FRIDAY", "THEIPIRAI", 7, 18, 13, "HASTHAM", 6, "Kanni", 26, "EKADASI", "KRISHNA"),
    _n("2026-12-06", "SUNDAY", "THEIPIRAI", 7, 20, 15, "SWATHI", 7, "Thulam", 28, "THRAYODASI", "KRISHNA"),
    _n("2026-12-10", "THURSDAY", "VALARPIRAI", 7, 24, 19, "MOOLAM", 9, "Dhanusu", 1, "PRATHAMA", "SHUKLA"),
    _n("2026-12-13", "SUNDAY", "VALARPIRAI", 7, 27, 22, "THIRUVONAM", 10, "Magaram", 4, "CHATHURTHI", "SHUKLA"),
    _n("2026-12-14", "MONDAY", "VALARPIRAI", 7, 28, 22, "THIRUVONAM", 10, "Magaram", 5, "PANCHAMI", "SHUKLA"),
)


_MUHURTHAM_NAALS_2027: tuple[MuhurthamNaal, ...] = (
    _n("2027-01-20", "WEDNESDAY", "VALARPIRAI", 9, 6, 5, "MIRUGASEERIDAM", 3, "Mithunam", 13, "THRAYODASI", "SHUKLA"),
    _n("2027-01-28", "THURSDAY", "VALARPIRAI", 9, 14, 14, "CHITHIRAI", 6, "Kanni", 22, "SAPTAMI", "KRISHNA"),
    _n("2027-02-08", "MONDAY", "THEIPIRAI", 9, 25, 24, "SADAYAM", 11, "Kumbam", 2, "DVITHIYAI", "SHUKLA"),
    _n("2027-02-10", "WEDNESDAY", "THEIPIRAI", 9, 27, 26, "UTHIRATTATHI", 12, "Meenam", 4, "CHATHURTHI", "SHUKLA"),
    _n("2027-02-11", "THURSDAY", "THEIPIRAI", 9, 28, 27, "REVATHI", 12, "Meenam", 5, "PANCHAMI", "SHUKLA"),
    _n("2027-02-12", "FRIDAY", "THEIPIRAI", 9, 29, 1, "ASWINI", 1, "Mesham", 6, "SHASHTI", "SHUKLA"),
    _n("2027-02-18", "THURSDAY", "THEIPIRAI", 10, 6, 7, "PUNARPOOSAM", 3, "Mithunam", 12, "DVADASI", "SHUKLA"),
    _n("2027-02-25", "THURSDAY", "VALARPIRAI", 10, 13, 14, "CHITHIRAI", 7, "Thulam", 20, "PANCHAMI", "KRISHNA"),
    _n("2027-02-26", "FRIDAY", "VALARPIRAI", 10, 14, 15, "SWATHI", 7, "Thulam", 21, "SHASHTI", "KRISHNA"),
    _n("2027-03-04", "THURSDAY", "THEIPIRAI", 10, 20, 21, "UTHIRADAM", 10, "Magaram", 26, "EKADASI", "KRISHNA"),
    _n("2027-03-10", "WEDNESDAY", "THEIPIRAI", 10, 26, 26, "UTHIRATTATHI", 12, "Meenam", 2, "DVITHIYAI", "SHUKLA"),
    _n("2027-03-11", "THURSDAY", "THEIPIRAI", 10, 27, 27, "REVATHI", 12, "Meenam", 3, "THRITHIYAI", "SHUKLA"),
    _n("2027-03-12", "FRIDAY", "THEIPIRAI", 10, 28, 1, "ASWINI", 1, "Mesham", 4, "CHATHURTHI", "SHUKLA"),
    _n("2027-03-15", "MONDAY", "THEIPIRAI", 11, 1, 4, "ROHINI", 2, "Rishabam", 7, "SAPTAMI", "SHUKLA"),
    _n("2027-03-17", "WEDNESDAY", "VALARPIRAI", 11, 3, 6, "THIRUVATHIRAI", 3, "Mithunam", 9, "NAVAMI", "SHUKLA"),
    _n("2027-03-18", "THURSDAY", "VALARPIRAI", 11, 4, 8, "POOSAM", 4, "Kadagam", 11, "EKADASI", "SHUKLA"),
    _n("2027-03-24", "WEDNESDAY", "VALARPIRAI", 11, 10, 14, "CHITHIRAI", 6, "Kanni", 17, "DVITHIYAI", "KRISHNA"),
    _n("2027-03-25", "THURSDAY", "VALARPIRAI", 11, 11, 15, "SWATHI", 7, "Thulam", 18, "THRITHIYAI", "KRISHNA"),
    _n("2027-04-01", "THURSDAY", "THEIPIRAI", 11, 18, 21, "UTHIRADAM", 10, "Magaram", 25, "DASAMI", "KRISHNA"),
    _n("2027-04-04", "SUNDAY", "THEIPIRAI", 11, 21, 24, "SADAYAM", 11, "Kumbam", 28, "THRAYODASI", "KRISHNA"),
    _n("2027-04-08", "THURSDAY", "THEIPIRAI", 11, 25, 1, "ASWINI", 1, "Mesham", 2, "DVITHIYAI", "SHUKLA"),
    _n("2027-04-11", "SUNDAY", "VALARPIRAI", 11, 28, 4, "ROHINI", 2, "Rishabam", 5, "PANCHAMI", "SHUKLA"),
    _n("2027-04-12", "MONDAY", "VALARPIRAI", 11, 29, 5, "MIRUGASEERIDAM", 3, "Mithunam", 6, "SHASHTI", "SHUKLA"),
    _n("2027-04-18", "SUNDAY", "VALARPIRAI", 0, 4, 11, "POORAM", 5, "Simmam", 12, "DVADASI", "SHUKLA"),
    _n("2027-04-23", "FRIDAY", "VALARPIRAI", 0, 9, 17, "ANUSHAM", 8, "Viruchigam", 18, "THRITHIYAI", "KRISHNA"),
    _n("2027-04-25", "SUNDAY", "VALARPIRAI", 0, 11, 18, "KETTAI", 8, "Viruchigam", 20, "PANCHAMI", "KRISHNA"),
    _n("2027-04-26", "MONDAY", "VALARPIRAI", 0, 12, 19, "MOOLAM", 9, "Dhanusu", 20, "PANCHAMI", "KRISHNA"),
    _n("2027-05-03", "MONDAY", "THEIPIRAI", 0, 19, 26, "UTHIRATTATHI", 12, "Meenam", 27, "DVADASI", "KRISHNA"),
    _n("2027-05-09", "SUNDAY", "THEIPIRAI", 0, 25, 5, "MIRUGASEERIDAM", 2, "Rishabam", 3, "THRITHIYAI", "SHUKLA"),
    _n("2027-05-12", "WEDNESDAY", "THEIPIRAI", 0, 28, 8, "POOSAM", 4, "Kadagam", 7, "SAPTAMI", "SHUKLA"),
    _n("2027-05-16", "SUNDAY", "VALARPIRAI", 1, 1, 12, "UTHIRAM", 6, "Kanni", 11, "EKADASI", "SHUKLA"),
    _n("2027-05-17", "MONDAY", "VALARPIRAI", 1, 2, 13, "HASTHAM", 6, "Kanni", 12, "DVADASI", "SHUKLA"),
    _n("2027-05-23", "SUNDAY", "VALARPIRAI", 1, 8, 19, "MOOLAM", 9, "Dhanusu", 18, "THRITHIYAI", "KRISHNA"),
    _n("2027-05-26", "WEDNESDAY", "VALARPIRAI", 1, 11, 22, "THIRUVONAM", 10, "Magaram", 21, "SHASHTI", "KRISHNA"),
    _n("2027-05-27", "THURSDAY", "VALARPIRAI", 1, 12, 23, "AVITTAM", 10, "Magaram", 22, "SAPTAMI", "KRISHNA"),
    _n("2027-05-28", "FRIDAY", "VALARPIRAI", 1, 13, 23, "AVITTAM", 11, "Kumbam", 22, "SAPTAMI", "KRISHNA"),
    _n("2027-06-07", "MONDAY", "THEIPIRAI", 1, 23, 7, "PUNARPOOSAM", 3, "Mithunam", 3, "THRITHIYAI", "SHUKLA"),
    _n("2027-06-10", "THURSDAY", "THEIPIRAI", 1, 26, 10, "MAGAM", 5, "Simmam", 6, "SHASHTI", "SHUKLA"),
    _n("2027-06-13", "SUNDAY", "VALARPIRAI", 1, 29, 13, "HASTHAM", 6, "Kanni", 10, "DASAMI", "SHUKLA"),
    _n("2027-06-14", "MONDAY", "VALARPIRAI", 1, 30, 14, "CHITHIRAI", 7, "Thulam", 11, "EKADASI", "SHUKLA"),
    _n("2027-06-23", "WEDNESDAY", "VALARPIRAI", 2, 8, 22, "THIRUVONAM", 10, "Magaram", 19, "CHATHURTHI", "KRISHNA"),
    _n("2027-06-24", "THURSDAY", "VALARPIRAI", 2, 9, 23, "AVITTAM", 11, "Kumbam", 20, "PANCHAMI", "KRISHNA"),
    _n("2027-06-25", "FRIDAY", "VALARPIRAI", 2, 10, 24, "SADAYAM", 11, "Kumbam", 21, "SHASHTI", "KRISHNA"),
    _n("2027-07-05", "MONDAY", "THEIPIRAI", 2, 20, 7, "PUNARPOOSAM", 4, "Kadagam", 2, "DVITHIYAI", "SHUKLA"),
    _n("2027-07-07", "WEDNESDAY", "THEIPIRAI", 2, 22, 10, "MAGAM", 5, "Simmam", 4, "CHATHURTHI", "SHUKLA"),
    _n("2027-07-09", "FRIDAY", "THEIPIRAI", 2, 24, 12, "UTHIRAM", 5, "Simmam", 6, "SHASHTI", "SHUKLA"),
    _n("2027-07-14", "WEDNESDAY", "THEIPIRAI", 2, 29, 17, "ANUSHAM", 8, "Viruchigam", 11, "EKADASI", "SHUKLA"),
    _n("2027-07-16", "FRIDAY", "THEIPIRAI", 2, 31, 19, "MOOLAM", 9, "Dhanusu", 13, "THRAYODASI", "SHUKLA"),
    _n("2027-08-20", "FRIDAY", "VALARPIRAI", 4, 3, 25, "POORATTATHI", 12, "Meenam", 18, "THRITHIYAI", "KRISHNA"),
    _n("2027-08-22", "SUNDAY", "THEIPIRAI", 4, 5, 27, "REVATHI", 12, "Meenam", 20, "PANCHAMI", "KRISHNA"),
    _n("2027-08-23", "MONDAY", "THEIPIRAI", 4, 6, 1, "ASWINI", 1, "Mesham", 21, "SHASHTI", "KRISHNA"),
    _n("2027-08-27", "FRIDAY", "THEIPIRAI", 4, 10, 5, "MIRUGASEERIDAM", 3, "Mithunam", 25, "DASAMI", "KRISHNA"),
    _n("2027-08-29", "SUNDAY", "THEIPIRAI", 4, 12, 7, "PUNARPOOSAM", 4, "Kadagam", 27, "DVADASI", "KRISHNA"),
    _n("2027-09-03", "FRIDAY", "THEIPIRAI", 4, 17, 13, "HASTHAM", 6, "Kanni", 3, "THRITHIYAI", "SHUKLA"),
    _n("2027-09-05", "SUNDAY", "VALARPIRAI", 4, 19, 15, "SWATHI", 7, "Thulam", 5, "PANCHAMI", "SHUKLA"),
    _n("2027-09-12", "SUNDAY", "VALARPIRAI", 4, 26, 22, "THIRUVONAM", 10, "Magaram", 12, "DVADASI", "SHUKLA"),
    _n("2027-09-13", "MONDAY", "VALARPIRAI", 4, 27, 22, "THIRUVONAM", 10, "Magaram", 13, "THRAYODASI", "SHUKLA"),
    _n("2027-10-20", "WEDNESDAY", "THEIPIRAI", 6, 3, 5, "MIRUGASEERIDAM", 2, "Rishabam", 20, "PANCHAMI", "KRISHNA"),
    _n("2027-10-22", "FRIDAY", "THEIPIRAI", 6, 5, 7, "PUNARPOOSAM", 3, "Mithunam", 22, "SAPTAMI", "KRISHNA"),
    _n("2027-10-27", "WEDNESDAY", "THEIPIRAI", 6, 10, 12, "UTHIRAM", 6, "Kanni", 28, "THRAYODASI", "KRISHNA"),
    _n("2027-11-01", "MONDAY", "THEIPIRAI", 6, 15, 17, "ANUSHAM", 8, "Viruchigam", 3, "THRITHIYAI", "SHUKLA"),
    _n("2027-11-05", "FRIDAY", "VALARPIRAI", 6, 19, 21, "UTHIRADAM", 10, "Magaram", 7, "SAPTAMI", "SHUKLA"),
    _n("2027-11-08", "MONDAY", "VALARPIRAI", 6, 22, 24, "SADAYAM", 11, "Kumbam", 10, "DASAMI", "SHUKLA"),
    _n("2027-11-10", "WEDNESDAY", "VALARPIRAI", 6, 24, 26, "UTHIRATTATHI", 12, "Meenam", 11, "EKADASI", "SHUKLA"),
    _n("2027-11-11", "THURSDAY", "VALARPIRAI", 6, 25, 26, "UTHIRATTATHI", 12, "Meenam", 12, "DVADASI", "SHUKLA"),
    _n("2027-11-12", "FRIDAY", "VALARPIRAI", 6, 26, 27, "REVATHI", 12, "Meenam", 13, "THRAYODASI", "SHUKLA"),
    _n("2027-11-15", "MONDAY", "THEIPIRAI", 6, 29, 3, "KARTHIGAI", 2, "Rishabam", 16, "PRATHAMA", "KRISHNA"),
    _n("2027-11-18", "THURSDAY", "THEIPIRAI", 7, 2, 7, "PUNARPOOSAM", 3, "Mithunam", 20, "PANCHAMI", "KRISHNA"),
    _n("2027-11-25", "THURSDAY", "THEIPIRAI", 7, 9, 14, "CHITHIRAI", 6, "Kanni", 27, "DVADASI", "KRISHNA"),
    _n("2027-12-02", "THURSDAY", "THEIPIRAI", 7, 16, 21, "UTHIRADAM", 9, "Dhanusu", 4, "CHATHURTHI", "SHUKLA"),
    _n("2027-12-05", "SUNDAY", "THEIPIRAI", 7, 19, 23, "AVITTAM", 11, "Kumbam", 7, "SAPTAMI", "SHUKLA"),
    _n("2027-12-08", "WEDNESDAY", "VALARPIRAI", 7, 22, 26, "UTHIRATTATHI", 12, "Meenam", 10, "DASAMI", "SHUKLA"),
    _n("2027-12-09", "THURSDAY", "VALARPIRAI", 7, 23, 27, "REVATHI", 12, "Meenam", 11, "EKADASI", "SHUKLA"),
    _n("2027-12-10", "FRIDAY", "VALARPIRAI", 7, 24, 1, "ASWINI", 1, "Mesham", 12, "DVADASI", "SHUKLA"),
)

# Registry of years for which a sourced almanac sheet exists.
MUHURTHAM_NAALS_BY_YEAR: dict[int, tuple[MuhurthamNaal, ...]] = {
    2026: _MUHURTHAM_NAALS_2026,
    2027: _MUHURTHAM_NAALS_2027,
}

MUHURTHAM_SOURCE = "Vinaadi sourced Tamil muhurtham almanac"


def available_years() -> list[int]:
    return sorted(MUHURTHAM_NAALS_BY_YEAR)


def get_muhurtham_naals(year: int) -> tuple[MuhurthamNaal, ...]:
    """Curated muhurtham naals for a year, or empty tuple if no sheet sourced."""
    return MUHURTHAM_NAALS_BY_YEAR.get(year, ())
