/**
 * FTR-20 — the mobile chart reading (app/reading/[id].tsx).
 *
 * Rendered on a real synthetic payload: the same captured explanation the web
 * reading-budget gate uses (web/components/chart-reading/__fixtures__/,
 * regenerated by scripts/capture_reading_fixture.py), so both surfaces are
 * tested on one answer. It carries the server's `story` picks (FTR-21).
 *
 * What it pins:
 *   - all five chapters render from the payload, headline first;
 *   - the planet rows expand to the server-picked why-lines;
 *   - the display boundary: no engine code (KARTARI_YOGA, KADAGAM, SATURN…)
 *     reaches the screen in either language.
 *
 * Blind spot: RNTL renders no layout, so this says nothing about how the
 * screen looks on a device, or whether the Tamil reads well.
 */
import React from "react";
import { fireEvent, render, screen, waitFor } from "@testing-library/react-native";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import type { ChartExplanationData } from "@vinaadi/shared";

import { getChartExplanation } from "@/api/charts";
import { useI18n } from "@/hooks/useI18n";

import ChartReadingScreen from "../app/reading/[id]";
import fixtures from "../../web/components/chart-reading/__fixtures__/synthetic-readings.json";

jest.mock("expo-router", () => ({
  router: { back: jest.fn(), push: jest.fn() },
  useLocalSearchParams: () => ({ id: "synthetic" }),
}));
jest.mock("@/hooks/useColors", () => ({ useColors: () => ({}) }));
jest.mock("@/hooks/useI18n", () => ({ useI18n: jest.fn(() => ({ lang: "en" })) }));
jest.mock("@/api/charts", () => ({ getChartExplanation: jest.fn() }));

const mockGet = jest.mocked(getChartExplanation);
const mockI18n = jest.mocked(useI18n);
const explanation = (fixtures as unknown as { explanation: ChartExplanationData }[])[0].explanation;

// UPPER_SNAKE engine codes, and bare upper-case graha/rasi codes.
const CODE = /\b[A-Z]{3,}_[A-Z_]+\b|\b(SUN|MOON|MARS|MERCURY|JUPITER|VENUS|SATURN|RAHU|KETU|KADAGAM|SIMMAM|MESHAM|MAGARAM|KUMBAM|MEENAM)\b/;

function renderScreen(lang: "en" | "ta") {
  mockI18n.mockReturnValue({ lang } as ReturnType<typeof useI18n>);
  mockGet.mockResolvedValue({ success: true, data: explanation } as Awaited<ReturnType<typeof getChartExplanation>>);
  // gcTime: Infinity — with the default, React Query schedules a 5-minute
  // cache-collection timer per query after unmount, which held this Jest
  // worker open ("A worker process has failed to exit gracefully").
  const client = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: Infinity } } });
  return render(
    <QueryClientProvider client={client}>
      <ChartReadingScreen />
    </QueryClientProvider>,
  );
}

type Node = { children?: (Node | string)[] | null } | string | null;

/** Rendered text only — style props and roles are not reading. */
function allText(): string {
  const out: string[] = [];
  const walk = (node: Node | Node[]) => {
    if (Array.isArray(node)) return node.forEach(walk);
    if (typeof node === "string") return void out.push(node);
    node?.children?.forEach(walk);
  };
  walk(screen.toJSON() as Node | Node[]);
  return out.join(" ");
}

describe("mobile chart reading", () => {
  it("opens on the server headline and walks all five chapters without an engine code", async () => {
    renderScreen("en");
    const headline = explanation.story?.headline?.en;
    expect({ headline: Boolean(headline), hint: "recapture the fixture" }).toEqual({ headline: true, hint: "recapture the fixture" });
    await waitFor(() => expect(screen.getByText(headline!)).toBeTruthy());
    for (const title of ["Who you are", "Your nine planets", "Running now", "Gifts & care", "What's coming"]) {
      fireEvent.press(screen.getByRole("tab", { name: new RegExp(title) }));
      const text = allText();
      expect({ title, code: text.match(CODE)?.[0] ?? null }).toEqual({ title, code: null });
    }
  });

  it("a planet row expands to its why-lines", async () => {
    renderScreen("en");
    await waitFor(() => expect(screen.getByRole("tab", { name: /Your nine planets/ })).toBeTruthy());
    fireEvent.press(screen.getByRole("tab", { name: /Your nine planets/ }));
    const before = allText().length;
    fireEvent.press(screen.getByText("Sun"));
    expect(allText().length).toBeGreaterThan(before);
  });

  it("Tamil mode carries no Latin rasi or graha name", async () => {
    renderScreen("ta");
    await waitFor(() => expect(screen.getByRole("tab", { name: /நீங்கள் யார்/ })).toBeTruthy());
    for (const title of ["நீங்கள் யார்", "உங்கள் ஒன்பது கிரகங்கள்", "இப்போது நடப்பது", "பலமும் கவனமும்", "வரவிருப்பவை"]) {
      fireEvent.press(screen.getByRole("tab", { name: new RegExp(title) }));
      const text = allText();
      expect({ title, latin: text.match(/\b(Sun|Moon|Mars|Mercury|Jupiter|Venus|Saturn|Kadagam|Simmam|Mesham|Magaram|Kumbam|Meenam)\b/i)?.[0] ?? null }).toEqual({ title, latin: null });
      expect({ title, code: text.match(CODE)?.[0] ?? null }).toEqual({ title, code: null });
    }
  });
});
