"""initial persistence

Revision ID: 83645c701aad
Revises: 
Create Date: 2026-05-21 12:39:14.262589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83645c701aad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_table('family_members',
    sa.Column('family_member_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('relationship', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], name=op.f('fk_family_members_owner_user_id_users')),
    sa.PrimaryKeyConstraint('family_member_id', name=op.f('pk_family_members'))
    )
    op.create_table('birth_profiles',
    sa.Column('birth_profile_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('family_member_id', sa.Uuid(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date_local', sa.Date(), nullable=False),
    sa.Column('birth_time_local', sa.Time(), nullable=True),
    sa.Column('birth_datetime_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('birth_place', sa.String(length=255), nullable=False),
    sa.Column('birth_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('birth_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('birth_timezone', sa.String(length=64), nullable=False),
    sa.Column('birth_time_source', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('birth_time_confidence_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('calendar_input_type', sa.String(length=32), server_default=sa.text("'gregorian'"), nullable=False),
    sa.Column('privacy_mode', sa.String(length=32), server_default=sa.text("'cloud'"), nullable=False),
    sa.Column('encrypted_birth_payload', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.family_member_id'], name=op.f('fk_birth_profiles_family_member_id_family_members')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], name=op.f('fk_birth_profiles_owner_user_id_users')),
    sa.PrimaryKeyConstraint('birth_profile_id', name=op.f('pk_birth_profiles'))
    )
    op.create_index(op.f('idx_birth_profiles_owner'), 'birth_profiles', ['owner_user_id'], unique=False)
    op.create_index(op.f('idx_birth_profiles_member'), 'birth_profiles', ['family_member_id'], unique=False)
    op.create_table('charts',
    sa.Column('chart_id', sa.Uuid(), nullable=False),
    sa.Column('birth_profile_id', sa.Uuid(), nullable=False),
    sa.Column('calculation_version', sa.Text(), nullable=False),
    sa.Column('ephemeris_provider', sa.String(length=64), server_default=sa.text("'SWISS_EPHEMERIS'"), nullable=False),
    sa.Column('ephemeris_version', sa.Text(), nullable=True),
    sa.Column('ayanamsa_type', sa.String(length=32), server_default=sa.text("'LAHIRI'"), nullable=False),
    sa.Column('ayanamsa_value_degrees', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('node_type', sa.String(length=32), server_default=sa.text("'MEAN_NODE'"), nullable=False),
    sa.Column('house_system_primary', sa.String(length=32), server_default=sa.text("'WHOLE_SIGN'"), nullable=False),
    sa.Column('julian_day', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('lagna_rasi', sa.String(length=32), nullable=False),
    sa.Column('lagna_longitude', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('moon_rasi', sa.String(length=32), nullable=False),
    sa.Column('janma_nakshatra', sa.String(length=32), nullable=False),
    sa.Column('janma_pada', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'completed'"), nullable=False),
    sa.Column('warnings', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed')", name=op.f('ck_charts_status_valid')),
    sa.CheckConstraint('janma_pada BETWEEN 1 AND 4', name=op.f('ck_charts_janma_pada_range')),
    sa.ForeignKeyConstraint(['birth_profile_id'], ['birth_profiles.birth_profile_id'], name=op.f('fk_charts_birth_profile_id_birth_profiles')),
    sa.PrimaryKeyConstraint('chart_id', name=op.f('pk_charts'))
    )
    op.create_index(op.f('idx_charts_birth_profile'), 'charts', ['birth_profile_id'], unique=False)
    op.create_index(op.f('idx_charts_calc_version'), 'charts', ['calculation_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_charts_calc_version'), table_name='charts')
    op.drop_index(op.f('idx_charts_birth_profile'), table_name='charts')
    op.drop_table('charts')
    op.drop_index(op.f('idx_birth_profiles_member'), table_name='birth_profiles')
    op.drop_index(op.f('idx_birth_profiles_owner'), table_name='birth_profiles')
    op.drop_table('birth_profiles')
    op.drop_table('family_members')
    op.drop_table('users')
    # ### end Alembic commands ###
