"""add_user_mode_and_goal_track

Revision ID: e19f02c4bfc9
Revises: g1a2b3c4d5e6
Create Date: 2026-05-27 14:29:27.357944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19f02c4bfc9'
down_revision: Union[str, Sequence[str], None] = 'g1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_mode', sa.String(length=20), server_default='BALANCED', nullable=False))
    op.add_column('users', sa.Column('goal_track', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'goal_track')
    op.drop_column('users', 'user_mode')
    # ### end Alembic commands ###
