/**
 * FTR-21 — the server's Story picks and the client selectors agree.
 *
 * `app/services/reading_story.py` now computes the Story view's selections
 * (headline, why-facets, active-now, top yogas, care column) once for every
 * surface; the selectors in reading-selectors.ts remain as the fallback for a
 * payload without `story`. Two copies of one rule drift unless something holds
 * them together, so this test runs both on the captured synthetic charts
 * (`__fixtures__/synthetic-readings.json`, regenerated by
 * scripts/capture_reading_fixture.py) and requires the same answer.
 *
 * Blind spot: two charts. A rule branch neither chart reaches (a cancelled
 * dosham, a STRONG activation tier) is covered only by the unit tests on each
 * side (reading-selectors.test.ts, tests/test_reading_story.py).
 */
import { describe, expect, it } from "vitest";

import type { ChartExplanationData } from "@/lib/types";

import fixtures from "./__fixtures__/synthetic-readings.json";
import { carePatterns, giftPatterns, isActiveNow, runningYogas, storyHeadline, whyFacets } from "./reading-selectors";

type Fixture = { name: string; explanation: ChartExplanationData };
const readings = fixtures as unknown as Fixture[];

describe.each(readings.map((r) => [r.name, r] as const))("server story = client selectors — %s", (_name, fixture) => {
  const story = fixture.explanation.story;
  const local: ChartExplanationData = { ...fixture.explanation, story: null };

  it("the fixture carries a server story (recapture it if not)", () => {
    expect(story).toBeTruthy();
  });

  it.each(["en", "ta"] as const)("headline (%s)", (lang) => {
    expect(storyHeadline(fixture.explanation, lang)).toBe(storyHeadline(local, lang));
  });

  it("why-facets and active-now, planet by planet", () => {
    for (const planet of fixture.explanation.planets) {
      const keys = (s: typeof story) => whyFacets(planet, s).map((f) => f.key);
      expect(keys(story), planet.graha).toEqual(keys(null));
      expect(isActiveNow(planet, story), planet.graha).toBe(isActiveNow(planet, null));
    }
  });

  it.each(["en", "ta"] as const)("yogas and the care column (%s)", (lang) => {
    const { yogas, doshams } = fixture.explanation.yogaDosham;
    expect(giftPatterns(yogas, lang, story)).toEqual(giftPatterns(yogas, lang, null));
    expect(runningYogas(yogas, lang, story)).toEqual(runningYogas(yogas, lang, null));
    expect(carePatterns(doshams, yogas, lang, story)).toEqual(carePatterns(doshams, yogas, lang, null));
  });
});
