"""Generate TypeScript transport types from the backend's own response schemas (A14).

    python scripts/generate_api_types.py            # rewrite the file
    python scripts/generate_api_types.py --check    # exit 1 if it is stale

Writes `packages/shared/src/generated/api-types.ts`: one interface per schema
component reachable from the 200 response of each operation in `OPERATIONS`,
plus one `<Operation>Response` alias per operation. Nothing here is hand-edited;
`tests/test_generated_api_types.py` regenerates it and fails on any difference.

Deliberately a small, dependency-free generator rather than a package: none was
installed (checked 2026-10-08), and this covers exactly the schema shapes
FastAPI emits for these models — objects, arrays, `$ref`, `anyOf` with null,
enums, maps and scalars. An unsupported shape raises instead of guessing.

The schemas are each route's response model in Pydantic's serialization mode,
with one change from what `app.openapi()` publishes: a model field that has a
default is *present*. OpenAPI's `required` leaves such a field out, so it would
generate as `x?: T`, yet model serialization writes every field on every
response. That holds only while nothing drops fields on the way out, so a route
with a `response_model_include/exclude*` flag is refused. A TypedDict's
`NotRequired` key really can be absent and stays optional. Component names are
the same as the published schema's.

The generated types are the *server's* claim. `packages/shared/src/api/
__contracts__/generated-fit.ts` asks `tsc` whether each one fits the
hand-written wrapper type that consumers actually use — the value-type and
nullability check the name-only field guard cannot make.

Grow it one coherent endpoint group at a time; it does not cover every route.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from pydantic.json_schema import GenerateJsonSchema, models_json_schema

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "packages" / "shared" / "src" / "generated" / "api-types.ts"

# (operation alias, OpenAPI path) — GET 200 responses. The nine operations A14
# gave schemas; extend deliberately.
OPERATIONS: tuple[tuple[str, str], ...] = (
    ("GetAshtottariDasha", "/api/v1/charts/{chart_id}/ashtottari-dasha"),
    ("GetAskVinaadiDailyStatus", "/api/v1/ask-vinaadi/daily-status"),
    ("GetCharaDasha", "/api/v1/charts/{chart_id}/chara-dasha"),
    ("GetConditionalDashas", "/api/v1/charts/{chart_id}/conditional-dashas"),
    ("GetKalachakraDasha", "/api/v1/charts/{chart_id}/kalachakra-dasha"),
    ("GetRemedyPlan", "/api/v1/charts/{chart_id}/remedy-plan"),
    ("GetShadbala", "/api/v1/charts/{chart_id}/shadbala"),
    ("GetVarshaphala", "/api/v1/charts/{chart_id}/varshaphala"),
    ("GetYoginiDasha", "/api/v1/charts/{chart_id}/yogini-dasha"),
    # Chart numerology GETs (flat responses, no envelope).
    ("GetBabyNames", "/api/v1/charts/{chart_id}/numerology/baby-names"),
    ("GetFavourableNumbers", "/api/v1/charts/{chart_id}/numerology/favourable-numbers"),
    ("GetLuckyDates", "/api/v1/charts/{chart_id}/numerology/lucky-dates"),
    ("GetMarriageDates", "/api/v1/charts/{chart_id}/numerology/marriage-dates"),
    ("GetNameSessions", "/api/v1/charts/{chart_id}/numerology/name-sessions"),
    ("GetPersonalCycle", "/api/v1/charts/{chart_id}/numerology/personal-cycle"),
)

HEADER = """\
// GENERATED by scripts/generate_api_types.py from the backend's response schemas.
// Do not edit by hand: change the Pydantic response model, then regenerate.
// tests/test_generated_api_types.py fails when this file is stale.
"""

REF_TEMPLATE = "#/components/schemas/{model}"

# Route options that make FastAPI leave fields out of the body, which would make
# "a defaulted field is present" false.
_FIELD_DROPPING_OPTIONS = (
    "response_model_include",
    "response_model_exclude",
    "response_model_exclude_unset",
    "response_model_exclude_defaults",
    "response_model_exclude_none",
)


class _SentFieldsSchema(GenerateJsonSchema):
    """Serialization mode in which a model field with a default is required."""

    def field_is_required(self, field: Any, total: bool) -> bool:
        if self.mode == "serialization" and field["type"] != "typed-dict-field":
            return field.get("serialization_exclude_if") is None
        return super().field_is_required(field, total)


def response_schemas(
    app: Any, operations: tuple[tuple[str, str], ...] = OPERATIONS
) -> tuple[list[tuple[str, dict]], dict[str, dict]]:
    """Each operation's 200 schema plus the components they reach, as sent."""
    from fastapi.routing import APIRoute  # noqa: PLC0415 — the script imports app lazily too

    routes = {route.path: route for route in app.routes if isinstance(route, APIRoute) and "GET" in route.methods}
    models = []
    for alias, path in operations:
        route = routes[path]
        dropping = [option for option in _FIELD_DROPPING_OPTIONS if getattr(route, option)]
        if dropping:
            raise ValueError(f"{alias}: {path} sets {dropping}; defaulted fields may be absent")
        if route.response_model is None:
            raise ValueError(f"{alias}: {path} declares no response model")
        models.append(route.response_model)
    keys, top = models_json_schema(
        [(model, "serialization") for model in dict.fromkeys(models)],
        schema_generator=_SentFieldsSchema,
        ref_template=REF_TEMPLATE,
    )
    roots = [(alias, keys[(model, "serialization")]) for (alias, _path), model in zip(operations, models, strict=True)]
    return roots, top.get("$defs", {})


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _identifier(component: str) -> str:
    """FastAPI may name a component `Model-Output`; TypeScript cannot."""
    return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in component)


def _ts(schema: dict, seen: set[str]) -> str:
    if "$ref" in schema:
        name = _ref_name(schema["$ref"])
        seen.add(name)
        return _identifier(name)
    if "anyOf" in schema:
        parts = [_ts(s, seen) for s in schema["anyOf"]]
        return " | ".join(dict.fromkeys(parts))
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "const" in schema:
        return json.dumps(schema["const"])
    kind = schema.get("type")
    if kind == "null":
        return "null"
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        inner = _ts(schema.get("items", {}), seen)
        return f"({inner})[]" if " | " in inner else f"{inner}[]"
    if kind == "object":
        extra = schema.get("additionalProperties")
        if schema.get("properties"):
            raise ValueError(f"inline object with properties is not supported: {schema}")
        if isinstance(extra, dict):
            return f"Record<string, {_ts(extra, seen)}>"
        return "Record<string, unknown>"
    raise ValueError(f"unsupported schema shape: {schema}")


def _interface(name: str, schema: dict, seen: set[str]) -> str:
    if schema.get("type") != "object" or "properties" not in schema:
        raise ValueError(f"component {name} is not a concrete object: {schema}")
    required = set(schema.get("required", []))
    lines = [f"export interface {_identifier(name)} {{"]
    for field, prop in schema["properties"].items():
        optional = "" if field in required else "?"
        lines.append(f"  {field}{optional}: {_ts(prop, seen)};")
    lines.append("}")
    return "\n".join(lines)


def render(schemas: tuple[list[tuple[str, dict]], dict[str, dict]]) -> str:
    operation_schemas, components = schemas
    roots: list[tuple[str, str]] = []
    pending: set[str] = set()
    for alias, schema in operation_schemas:
        roots.append((alias, _ts(schema, pending)))

    emitted: dict[str, str] = {}
    while pending:
        name = pending.pop()
        if name in emitted:
            continue
        found: set[str] = set()
        emitted[name] = _interface(name, components[name], found)
        pending |= found - set(emitted)

    blocks = [HEADER.rstrip("\n")]
    blocks += [emitted[name] for name in sorted(emitted)]
    blocks.append("\n".join(f"export type {alias}Response = {root};" for alias, root in roots))
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()

    sys.path.insert(0, str(REPO))
    from app.main import app  # noqa: PLC0415 — needs the repo on sys.path first

    text = render(response_schemas(app))
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.relative_to(REPO)} is stale — run scripts/generate_api_types.py")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
