"""Generate TypeScript transport types from the backend's own OpenAPI schema (A14).

    python scripts/generate_api_types.py            # rewrite the file
    python scripts/generate_api_types.py --check    # exit 1 if it is stale

Writes `packages/shared/src/generated/api-types.ts`: one interface per schema
component reachable from the 200 response of each operation in `OPERATIONS`,
plus one `<Operation>Response` alias per operation. Nothing here is hand-edited;
`tests/test_generated_api_types.py` regenerates it and fails on any difference.

Deliberately a small, dependency-free generator rather than a package: none was
installed (checked 2026-10-08), and this covers exactly the schema shapes
FastAPI emits for these models — objects, arrays, `$ref`, `anyOf` with null,
enums, maps and scalars. An unsupported shape raises instead of guessing.

The generated types are the *server's* claim. `packages/shared/src/api/
__contracts__/generated-fit.ts` asks `tsc` whether each one fits the
hand-written wrapper type that consumers actually use — the value-type and
nullability check the name-only field guard cannot make.

Grow it one coherent endpoint group at a time; it does not cover every route.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "packages" / "shared" / "src" / "generated" / "api-types.ts"

# (operation alias, OpenAPI path) — GET 200 responses. The nine operations A14
# gave schemas; extend deliberately.
OPERATIONS: tuple[tuple[str, str], ...] = (
    ("GetAshtottariDasha", "/api/v1/charts/{chart_id}/ashtottari-dasha"),
    ("GetAskVinaadiDailyStatus", "/api/v1/ask-vinaadi/daily-status"),
    ("GetCharaDasha", "/api/v1/charts/{chart_id}/chara-dasha"),
    ("GetConditionalDashas", "/api/v1/charts/{chart_id}/conditional-dashas"),
    ("GetKalachakraDasha", "/api/v1/charts/{chart_id}/kalachakra-dasha"),
    ("GetRemedyPlan", "/api/v1/charts/{chart_id}/remedy-plan"),
    ("GetShadbala", "/api/v1/charts/{chart_id}/shadbala"),
    ("GetVarshaphala", "/api/v1/charts/{chart_id}/varshaphala"),
    ("GetYoginiDasha", "/api/v1/charts/{chart_id}/yogini-dasha"),
)

HEADER = """\
// GENERATED by scripts/generate_api_types.py from the backend's OpenAPI schema.
// Do not edit by hand: change the Pydantic response model, then regenerate.
// tests/test_generated_api_types.py fails when this file is stale.
"""


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _identifier(component: str) -> str:
    """FastAPI may name a component `Model-Output`; TypeScript cannot."""
    return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in component)


def _ts(schema: dict, seen: set[str]) -> str:
    if "$ref" in schema:
        name = _ref_name(schema["$ref"])
        seen.add(name)
        return _identifier(name)
    if "anyOf" in schema:
        parts = [_ts(s, seen) for s in schema["anyOf"]]
        return " | ".join(dict.fromkeys(parts))
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "const" in schema:
        return json.dumps(schema["const"])
    kind = schema.get("type")
    if kind == "null":
        return "null"
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        inner = _ts(schema.get("items", {}), seen)
        return f"({inner})[]" if " | " in inner else f"{inner}[]"
    if kind == "object":
        extra = schema.get("additionalProperties")
        if schema.get("properties"):
            raise ValueError(f"inline object with properties is not supported: {schema}")
        if isinstance(extra, dict):
            return f"Record<string, {_ts(extra, seen)}>"
        return "Record<string, unknown>"
    raise ValueError(f"unsupported schema shape: {schema}")


def _interface(name: str, schema: dict, seen: set[str]) -> str:
    if schema.get("type") != "object" or "properties" not in schema:
        raise ValueError(f"component {name} is not a concrete object: {schema}")
    required = set(schema.get("required", []))
    lines = [f"export interface {_identifier(name)} {{"]
    for field, prop in schema["properties"].items():
        optional = "" if field in required else "?"
        lines.append(f"  {field}{optional}: {_ts(prop, seen)};")
    lines.append("}")
    return "\n".join(lines)


def render(spec: dict) -> str:
    components = spec.get("components", {}).get("schemas", {})
    roots: list[tuple[str, str]] = []
    pending: set[str] = set()
    for alias, path in OPERATIONS:
        schema = spec["paths"][path]["get"]["responses"]["200"]["content"]["application/json"]["schema"]
        roots.append((alias, _ts(schema, pending)))

    emitted: dict[str, str] = {}
    while pending:
        name = pending.pop()
        if name in emitted:
            continue
        found: set[str] = set()
        emitted[name] = _interface(name, components[name], found)
        pending |= found - set(emitted)

    blocks = [HEADER.rstrip("\n")]
    blocks += [emitted[name] for name in sorted(emitted)]
    blocks.append("\n".join(f"export type {alias}Response = {root};" for alias, root in roots))
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()

    sys.path.insert(0, str(REPO))
    from app.main import app  # noqa: PLC0415 — needs the repo on sys.path first

    text = render(app.openapi())
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.relative_to(REPO)} is stale — run scripts/generate_api_types.py")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
