"""Independent NOAA/Meeus sunrise+sunset, used to generate and re-verify the
reference values pinned in tests/test_wi07_sunrise_validation_harness.py.

**Why this file exists in the repo.** WI-07's original cross-check leg was
generated by a script that was never committed — only its output numbers were.
When the sunrise convention was re-ruled on 2026-09-29 the whole leg had to be
rewritten from scratch to regenerate the values, because there was nothing to
re-run. Pinned reference numbers whose generator is lost are unverifiable: the
next reader cannot tell a correct value from a typo. Keep this committed.

**What it is.** A direct implementation of the NOAA Solar Calculator equations
(Meeus, *Astronomical Algorithms*), sharing no code with Swiss Ephemeris or
with app/calculations/ephemeris.py. That independence is the entire point — a
cross-check computed by the code under test proves only that the code is
self-consistent.

**Convention.** Zenith 90.833 deg (altitude -0.833 deg) = mean atmospheric
refraction at the horizon (~34') plus the Sun's semi-diameter (~16'), i.e. the
apparent upper-limb event. This is Vinaadi's Thirukanitham convention (see
SunriseConvention in app/calculations/ephemeris.py).

**Accuracy.** NOAA's equations are a truncated series; they agree with Swiss
Ephemeris to ~20 s at these latitudes and dates, which is why the harness
asserts a 120 s band rather than an exact match. A disagreement of minutes
means a real bug; a disagreement of seconds does not.

Run:  .venv/Scripts/python.exe scripts/sunrise_reference_crosscheck.py
"""
from __future__ import annotations

import math
from datetime import UTC, date, datetime, timedelta
from zoneinfo import ZoneInfo

#: Altitude of the Sun's centre at the apparent upper-limb rise/set event,
#: expressed as a zenith angle. 90 + 0.833 deg.
APPARENT_ZENITH_DEG = 90.833

#: Rahu Kalam occupies one eighth of the sunrise->sunset span; which eighth is
#: a fixed weekday lookup, not a calculation. Keyed by datetime.weekday()
#: (Monday=0), value is the 1-indexed segment.
RAHU_KALAM_SEGMENT_BY_WEEKDAY = {0: 2, 1: 7, 2: 5, 3: 6, 4: 4, 5: 3, 6: 8}

_UNIX_EPOCH_JD = 2440587.5


def _julian_day(d: date) -> float:
    delta = datetime(d.year, d.month, d.day, tzinfo=UTC) - datetime(1970, 1, 1, tzinfo=UTC)
    return _UNIX_EPOCH_JD + delta.total_seconds() / 86400.0


def _solar_declination_and_eqtime(jd: float) -> tuple[float, float]:
    """Return (declination in radians, equation of time in minutes)."""
    t = (jd - 2451545.0) / 36525.0
    mean_long = (280.46646 + t * (36000.76983 + t * 0.0003032)) % 360.0
    mean_anom = 357.52911 + t * (35999.05029 - 0.0001537 * t)
    eccentricity = 0.016708634 - t * (0.000042037 + 0.0000001267 * t)

    anom_rad = math.radians(mean_anom)
    centre = (
        math.sin(anom_rad) * (1.914602 - t * (0.004817 + 0.000014 * t))
        + math.sin(2 * anom_rad) * (0.019993 - 0.000101 * t)
        + math.sin(3 * anom_rad) * 0.000289
    )
    true_long = mean_long + centre

    omega = math.radians(125.04 - 1934.136 * t)
    apparent_long = math.radians(true_long - 0.00569 - 0.00478 * math.sin(omega))

    mean_obliquity = 23.0 + (26.0 + (21.448 - t * (46.815 + t * (0.00059 - t * 0.001813))) / 60.0) / 60.0
    obliquity = math.radians(mean_obliquity + 0.00256 * math.cos(omega))

    declination = math.asin(math.sin(obliquity) * math.sin(apparent_long))

    y = math.tan(obliquity / 2.0) ** 2
    long_rad = math.radians(mean_long)
    eqtime = 4.0 * math.degrees(
        y * math.sin(2 * long_rad)
        - 2 * eccentricity * math.sin(anom_rad)
        + 4 * eccentricity * y * math.sin(anom_rad) * math.cos(2 * long_rad)
        - 0.5 * y * y * math.sin(4 * long_rad)
        - 1.25 * eccentricity * eccentricity * math.sin(2 * anom_rad)
    )
    return declination, eqtime


def apparent_rise_set(
    day: date,
    latitude: float,
    longitude: float,
    *,
    zenith_deg: float = APPARENT_ZENITH_DEG,
) -> tuple[datetime, datetime] | tuple[None, None]:
    """Apparent sunrise and sunset as aware UTC datetimes, or (None, None) when
    the Sun stays above or below the horizon all day."""
    jd_midnight = _julian_day(day)
    lat_rad = math.radians(latitude)
    events: list[datetime] = []

    for is_rise in (True, False):
        guess = jd_midnight + 0.5  # start from approximate local noon
        minutes = 0.0
        # Three passes: the declination/eqtime used must be those at the event,
        # not at midnight, and one pass leaves a few seconds of error.
        for _ in range(3):
            declination, eqtime = _solar_declination_and_eqtime(guess)
            cos_hour_angle = (
                math.cos(math.radians(zenith_deg)) / (math.cos(lat_rad) * math.cos(declination))
                - math.tan(lat_rad) * math.tan(declination)
            )
            if not -1.0 <= cos_hour_angle <= 1.0:
                return None, None
            hour_angle = math.degrees(math.acos(cos_hour_angle))
            minutes = 720.0 - 4.0 * (longitude + (hour_angle if is_rise else -hour_angle)) - eqtime
            guess = jd_midnight + minutes / 1440.0
        events.append(datetime(day.year, day.month, day.day, tzinfo=UTC) + timedelta(minutes=minutes))

    return events[0], events[1]


def rahu_kalam_start(sunrise_local: datetime, sunset_local: datetime) -> datetime:
    segment = RAHU_KALAM_SEGMENT_BY_WEEKDAY[sunrise_local.weekday()]
    return sunrise_local + (sunset_local - sunrise_local) * (segment - 1) / 8.0


#: The same 6 dates x 2 locations the harness pins: spread across solstices and
#: equinoxes where day-length effects are largest, at a Tamil-Nadu latitude and
#: at a northern diaspora latitude where the refraction term matters far more.
CASES: tuple[tuple[str, date, float, float, str], ...] = (
    ("Chennai — Jan", date(2026, 1, 15), 13.0827, 80.2707, "Asia/Kolkata"),
    ("Chennai — Mar equinox", date(2026, 3, 20), 13.0827, 80.2707, "Asia/Kolkata"),
    ("Chennai — Jun solstice", date(2026, 6, 21), 13.0827, 80.2707, "Asia/Kolkata"),
    ("Chennai — Sep equinox", date(2026, 9, 22), 13.0827, 80.2707, "Asia/Kolkata"),
    ("Chennai — Oct", date(2026, 10, 10), 13.0827, 80.2707, "Asia/Kolkata"),
    ("Chennai — Dec solstice", date(2026, 12, 21), 13.0827, 80.2707, "Asia/Kolkata"),
    ("Toronto — Jan", date(2026, 1, 15), 43.6532, -79.3832, "America/Toronto"),
    ("Toronto — Mar equinox", date(2026, 3, 20), 43.6532, -79.3832, "America/Toronto"),
    ("Toronto — Jun solstice", date(2026, 6, 21), 43.6532, -79.3832, "America/Toronto"),
    ("Toronto — Sep equinox", date(2026, 9, 22), 43.6532, -79.3832, "America/Toronto"),
    ("Toronto — Oct", date(2026, 10, 10), 43.6532, -79.3832, "America/Toronto"),
    ("Toronto — Dec solstice", date(2026, 12, 21), 43.6532, -79.3832, "America/Toronto"),
)


def main() -> None:
    # Imported here so the NOAA maths above stays importable without the app.
    from app.services.panchangam_cache import calculate_daily_panchangam

    print(f"{'case':24s} {'NOAA rise':>9s} {'swe rise':>9s} {'d(s)':>5s}   {'NOAA rahu':>9s} {'swe rahu':>9s} {'d(s)':>5s}")
    worst_rise = worst_rahu = 0.0
    rows: list[str] = []

    for label, day, lat, lon, tz_name in CASES:
        tz = ZoneInfo(tz_name)
        rise_utc, set_utc = apparent_rise_set(day, lat, lon)
        if rise_utc is None or set_utc is None:
            raise RuntimeError(f"{label}: Sun is circumpolar — no rise/set to compare")
        rise = rise_utc.astimezone(tz).replace(tzinfo=None)
        sunset = set_utc.astimezone(tz).replace(tzinfo=None)
        rahu = rahu_kalam_start(rise, sunset)

        snapshot = calculate_daily_panchangam(day, lat, lon, tz_name)
        swe_rise = snapshot.sunrise.replace(tzinfo=None)
        swe_rahu = snapshot.rahu_kalam.start.replace(tzinfo=None)

        d_rise = abs((rise - swe_rise).total_seconds())
        d_rahu = abs((rahu - swe_rahu).total_seconds())
        worst_rise = max(worst_rise, d_rise)
        worst_rahu = max(worst_rahu, d_rahu)

        print(
            f"{label:24s} {rise:%H:%M:%S} {swe_rise:%H:%M:%S} {d_rise:5.0f}   "
            f"{rahu:%H:%M:%S} {swe_rahu:%H:%M:%S} {d_rahu:5.0f}"
        )
        rows.append(
            f'    ReferenceCase("{label}", date({day.year}, {day.month}, {day.day}), '
            f'{lat}, {lon}, "{tz_name}", "{rise:%H:%M}", "{rahu:%H:%M}", _CROSSCHECK_SOURCE),'
        )

    print(f"\nworst sunrise delta {worst_rise:.0f}s, worst Rahu Kalam delta {worst_rahu:.0f}s")
    print("(harness asserts a 120s band; a delta in minutes means a real bug)\n")
    print("--- paste into COMPUTATIONAL_CROSSCHECK_CASES ---")
    for row in rows:
        print(row)


if __name__ == "__main__":
    main()
