"""Tamil solar calendar (Thirukanitham) date conversion.

The Tamil month is the sidereal rasi the Sun occupies: the Sun's entry into a
rasi (sankranti) begins a new Tamil month. The month's first civil day is the
sankranti day itself if the sankranti instant falls before that day's sunset;
otherwise the first day is the day after. The day-of-month is the civil-day
count since that first day (=1).

    Mesha   -> Chithirai     Thula      -> Aippasi
    Rishaba -> Vaikasi       Vrischika  -> Karthigai
    Mithuna -> Aani          Dhanu      -> Margazhi
    Kataka  -> Aadi          Makara     -> Thai
    Simha   -> Aavani        Kumbha     -> Maasi
    Kanni   -> Purattasi     Meena      -> Panguni

Doctrine A-3 — the sunset threshold, with a published-calendar correction
-----------------------------------------------------------
Status 2026-08-19. The sunset threshold is the default rule this module
implements, and it reproduces the Puthandu anchor. Vinaadi's selected
authority, Sri Gnanananda Panchangam (2026–27), places Aavani 1, 2026 on 18
August, so that published boundary set is applied below.

**Why the sunset threshold.** It reproduces the gazetted Puthandu. Chithirai 1,
2026 = 14 April is published by the Tamil Nadu government and is independently
carried in our own festival table. The Chithirai sankranti is 14 Apr 09:32:39
IST (Chennai, drik/Lahiri) — after sunrise, before sunset — so only a threshold
at or later than 09:32 assigns it to 14 April. The sunrise convention puts
Puthandu on 15 April and is excluded by the anchor.

The two conventions disagree on **8 of the 12 months** of Tamil year 2026-27:
Chithirai, Vaikasi, Aani, Aavani, Purattasi, Margazhi, Maasi, Panguni. That
count is *derived, not asserted* — the full table, with every sankranti instant
and both rules' answers, is published in
`docs/TAMIL_MONTH_BOUNDARY_TABLE_2026-27.md` and regenerated by
`scripts/derive_tamil_month_boundaries.py`. An earlier revision of this
docstring stated the same number with no table behind it; that was the sort of
checkable-but-unchecked claim this file exists to stop.

The correction is deliberately a named month-start date rather than a change to
the astronomical calculation or a new universal threshold: the two dates cannot
be reconciled by one threshold rule. This keeps every other solar-month
boundary on the existing Lahiri/sunset calculation while matching the published
Tamil calendar that users see for this specific boundary.

Note: relies on the swisseph ephemeris (via `_sun_sidereal_longitude_at_jd` and
`calculate_rise_transit_jd`). Verify output in an environment where swisseph is
available before relying on it.
"""
from __future__ import annotations

from datetime import UTC, date, datetime, time, timedelta
from zoneinfo import ZoneInfo

from app.calculations.astro import (
    julian_day_to_utc_datetime,
    normalize_longitude,
    utc_datetime_to_julian_day,
)
from app.calculations.ephemeris import calculate_rise_transit_jd

# Aliased to name the contract this module depends on. `sun_longitude_at_jd`
# returns a SIDEREAL (Lahiri) longitude — `calculate_sidereal_planets` calls
# `set_lahiri_ayanamsa()` and passes SEFLG_SIDEREAL unconditionally. Every rasi
# index derived below is meaningless against a tropical longitude, and the bare
# name does not say which it is, so the alias says it here where it is used.
from app.calculations.ephemeris import sun_longitude_at_jd as _sun_sidereal_longitude_at_jd
from app.data.tamil_calendar_authority import published_month_start_date

# Index 0 == Mesha == Chithirai
TAMIL_MONTHS: list[tuple[str, str]] = [
    ("சித்திரை", "Chithirai"),
    ("வைகாசி", "Vaikasi"),
    ("ஆனி", "Aani"),
    ("ஆடி", "Aadi"),
    ("ஆவணி", "Aavani"),
    ("புரட்டாசி", "Purattasi"),
    ("ஐப்பசி", "Aippasi"),
    ("கார்த்திகை", "Karthigai"),
    ("மார்கழி", "Margazhi"),
    ("தை", "Thai"),
    ("மாசி", "Maasi"),
    ("பங்குனி", "Panguni"),
]

_MAX_MONTH_DAYS = 33  # solar months never exceed ~31-32 days; safety bound for the walk-back

def _local_midnight_jd(d: date, tz: ZoneInfo) -> float:
    midnight_local = datetime.combine(d, time(0, 0), tzinfo=tz)
    return utc_datetime_to_julian_day(midnight_local.astimezone(UTC))


def _sunrise_jd(d: date, tz: ZoneInfo, latitude: float, longitude: float) -> float:
    return calculate_rise_transit_jd(_local_midnight_jd(d, tz), latitude, longitude, rise=True)


def _sunset_jd(d: date, tz: ZoneInfo, latitude: float, longitude: float) -> float:
    sunrise_jd = _sunrise_jd(d, tz, latitude, longitude)
    return calculate_rise_transit_jd(sunrise_jd, latitude, longitude, rise=False)


def _sun_rasi_index_at_jd(jd: float) -> int:
    """Sidereal rasi index (0=Mesha) of the Sun at Julian Day `jd`."""
    return int(normalize_longitude(_sun_sidereal_longitude_at_jd(jd)) // 30) % 12


# ---------------------------------------------------------------------------
# Step 1 of 2 — ASTRONOMY. When did the Sun actually cross into the rasi?
#
# This half is not doctrine and does not change when doctrine does. It is
# separated from the civil-day assignment below precisely so that the open
# Aavani question (see module docstring) can be resolved — by swapping the
# threshold, branching Vakya vs Thirukanitham, or anything else — without
# anyone editing a bisection search to do it.
# ---------------------------------------------------------------------------

def find_sankranti_jd(rasi: int, before_jd: float) -> float:
    """Find the JD when the Sun entered `rasi`.

    `before_jd` must fall within `rasi` (i.e. the Sun is already in that rasi
    at that instant). Walks backward a day at a time until the rasi differs,
    then bisects the bracketed day to the exact crossing instant — mirroring
    the boundary-finding approach used for tithi/yoga in panchangam.py.

    Public despite starting life underscored: `tests/test_panchangam.py` was
    already importing it across a module boundary to pin Makara sankranti
    precision for Thai Pongal, which made the underscore a fiction.
    """
    hi = before_jd
    lo = before_jd - 1.0
    steps = 0
    while _sun_rasi_index_at_jd(lo) == rasi:
        hi = lo
        lo -= 1.0
        steps += 1
        if steps > _MAX_MONTH_DAYS:
            raise ValueError("sankranti search exceeded maximum solar month length")

    base_angle = normalize_longitude(_sun_sidereal_longitude_at_jd(lo))
    target_angle = rasi * 30.0
    continuous_target = target_angle if target_angle >= base_angle else target_angle + 360.0
    for _ in range(64):
        mid = (lo + hi) / 2
        angle = normalize_longitude(_sun_sidereal_longitude_at_jd(mid))
        if angle < base_angle - 180.0:
            angle += 360.0
        if angle >= continuous_target:
            hi = mid
        else:
            lo = mid
    return hi


# ---------------------------------------------------------------------------
# Step 2 of 2 — DOCTRINE. Which civil day does that crossing begin?
#
# This is the half that assigns a civil date. Everything the module asserts
# about Tamil calendar convention lives in this one function.
# ---------------------------------------------------------------------------

def month_start_date_for_sankranti(
    sankranti_jd: float,
    tz: ZoneInfo,
    latitude: float,
    longitude: float,
    rasi: int | None = None,
) -> date:
    """Return the civil date on which the month opened by `sankranti_jd` begins.

    Implements the sunset threshold (doctrine A-3): before that day's sunset
    starts the month the same day, otherwise the day after. A verified,
    published calendar boundary may override that default for a specific Tamil
    month and year; this is intentionally separate from the astronomical step.

    Tie convention: the comparison is strict, so a sankranti falling *exactly*
    at the sunset instant starts the month the following day. That is a
    convention rather than a sourced rule — both values are computed floats and
    exact equality has measure zero. It is recorded here instead of being
    smoothed over with an epsilon, which would only relocate the arbitrary
    boundary rather than remove it.
    """
    sankranti_date = julian_day_to_utc_datetime(sankranti_jd).astimezone(tz).date()
    if rasi is not None and tz.key == "Asia/Kolkata":
        published_start = published_month_start_date(
            gregorian_year=sankranti_date.year,
            rasi=rasi,
        )
        if published_start is not None:
            return published_start

    sankranti_sunset_jd = _sunset_jd(sankranti_date, tz, latitude, longitude)

    if sankranti_jd < sankranti_sunset_jd:
        return sankranti_date
    return sankranti_date + timedelta(days=1)


def tamil_solar_date(d: date, timezone_name: str, latitude: float, longitude: float) -> tuple[int, int]:
    """Return (month_index 0..11, day_of_month starting at 1) for civil date `d`.

    The Tamil month is the sidereal rasi the Sun occupies at sunset on `d`; the
    civil day on which that month began is decided by
    `month_start_date_for_sankranti`.
    """
    tz = ZoneInfo(timezone_name)
    sunset_jd = _sunset_jd(d, tz, latitude, longitude)
    rasi = _sun_rasi_index_at_jd(sunset_jd)

    sankranti_jd = find_sankranti_jd(rasi, sunset_jd)
    month_start_date = month_start_date_for_sankranti(sankranti_jd, tz, latitude, longitude, rasi)

    # A published month start can fall after the Sun has already entered the
    # new rasi at sunset. On that intervening civil day, report the final day
    # of the prior Tamil month rather than a day zero of the new one.
    if d < month_start_date:
        rasi = (rasi - 1) % 12
        prior_sankranti_jd = find_sankranti_jd(rasi, sankranti_jd - 1e-9)
        month_start_date = month_start_date_for_sankranti(
            prior_sankranti_jd,
            tz,
            latitude,
            longitude,
            rasi,
        )

    day_of_month = (d - month_start_date).days + 1
    return rasi, day_of_month


def format_tamil_date(d: date, timezone_name: str, latitude: float, longitude: float) -> tuple[str, str]:
    """Return (tamil_text, english_text), e.g. ("ஆடி 15", "Aadi 15")."""
    rasi, day = tamil_solar_date(d, timezone_name, latitude, longitude)
    ta, en = TAMIL_MONTHS[rasi]
    return f"{ta} {day}", f"{en} {day}"
